/**
 * Query-related types for DbRevel SDK
 * @packageDocumentation
 */

/**
 * Represents a single database query generated by the AI
 *
 * @example
 * ```typescript
 * const query: DatabaseQuery = {
 *   database: "postgres",
 *   query_type: "sql",
 *   query: "SELECT * FROM users WHERE city = $1",
 *   parameters: ["Lagos"],
 *   estimated_rows: 100
 * };
 * ```
 */
export interface DatabaseQuery {
	/** Name of the target database (e.g., "postgres", "mongodb") */
	database: string;
	/** Type of query being executed */
	query_type: "sql" | "mongodb" | "cross-db";
	/** The query string (SQL) or aggregation pipeline (MongoDB) */
	query: string | Array<Record<string, any>>;
	/** Parameterized values for the query (prevents SQL injection) */
	parameters?: any[];
	/** Estimated number of rows the query will return */
	estimated_rows?: number;
	/** MongoDB collection name (only for MongoDB queries) */
	collection?: string;
}

/**
 * Execution plan generated by the AI for a natural language query
 *
 * @example
 * ```typescript
 * const plan: QueryPlan = {
 *   databases: ["postgres"],
 *   queries: [...],
 *   security_applied: ["row_level_security", "parameterized_queries"],
 *   estimated_cost: "low"
 * };
 * ```
 */
export interface QueryPlan {
	/** List of databases that will be queried */
	databases: string[];
	/** Individual queries to be executed */
	queries: DatabaseQuery[];
	/** Strategy for joining results from multiple databases */
	join_strategy?: string;
	/** AI's reasoning for the query plan */
	reasoning?: string;
	/** Security measures applied to the query */
	security_applied: string[];
	/** Estimated computational cost: "low", "medium", or "high" */
	estimated_cost: string;
}

/**
 * Metadata about query execution
 *
 * @example
 * ```typescript
 * const metadata: QueryMetadata = {
 *   query_plan: { ... },
 *   execution_time_ms: 45,
 *   rows_returned: 10,
 *   gemini_tokens_used: 150,
 *   trace_id: "abc-123",
 *   timestamp: "2024-01-15T10:30:00Z",
 *   cached: false
 * };
 * ```
 */
export interface QueryMetadata {
	/** The execution plan used for this query */
	query_plan: QueryPlan;
	/** Total execution time in milliseconds */
	execution_time_ms: number;
	/** Number of rows/documents returned */
	rows_returned: number;
	/** Number of Gemini AI tokens consumed */
	gemini_tokens_used: number;
	/** Unique identifier for tracing/debugging this request */
	trace_id: string;
	/** ISO 8601 timestamp of when the query was executed */
	timestamp: string;
	/** Whether the result was served from cache */
	cached: boolean;
}

/**
 * Result of a database query with typed data
 *
 * @typeParam T - The type of each row/document in the result
 *
 * @example
 * ```typescript
 * interface User {
 *   id: number;
 *   name: string;
 *   email: string;
 * }
 *
 * const result: QueryResult<User> = await client.query<User>("Get all users");
 * result.data.forEach(user => console.log(user.name));
 * ```
 */
export interface QueryResult<T = any> {
	/** Array of result rows/documents */
	data: T[];
	/** Execution metadata including timing, tokens, and query plan */
	metadata: QueryMetadata;
}
