"""Custom exception classes for the application."""


class DbrevelError(Exception):
    """Base exception class for all application-specific errors."""
    pass


class QueryValidationError(DbrevelError):
    """Raised when a query fails validation."""
    pass


class InvalidQueryError(DbrevelError):
    """Raised when a query has an invalid format."""
    pass


class MissingCollectionError(DbrevelError):
    """Raised when a MongoDB query is missing the collection name."""
    pass


class UnsupportedQueryError(DbrevelError):
    """Raised for unsupported query types."""
    pass


class GeminiError(DbrevelError):
    """Base class for all Gemini-related errors."""
    pass


class GeminiAPIError(GeminiError):
    """For errors returned by the Gemini API."""
    pass


class GeminiResponseError(GeminiError):
    """For errors related to the format of the Gemini API response."""
    pass


class InvalidJSONError(GeminiError):
    """When the response from Gemini is not valid JSON."""
    pass


class InvalidQueryPlanError(GeminiError):
    """When the query plan generated by Gemini is invalid."""
    pass


class MissingBYOApiKeyError(DbrevelError):
    """When the account is configured for BYO Gemini but no API key is set."""
    pass
